### ISSUE TITLE
No route found for IPv6 destination

### ISSUE THREAD

**Issue by anu171** [medbenali/CyberScan#4]
root@kali:~/tools/CyberScan# ls
 CyberScan.py      LICENSE       README.md    doc      libs      scapy
 GeoLiteCity.dat  'PCAP Files'   banner.txt   images   pygeoip   test.pcap
root@kali:~/tools/CyberScan# python CyberScan.py -v
WARNING: No route found for IPv6 destination :: (no default route?)
1.1.1
root@kali:~/tools/CyberScan# 
please help me i could not install CyberScan??? how to fix this????

thanks in advance...

**Comment by medbenali** [comment]
It's not a bug continue hacking no error to verify it print the version of CyberScan 1.1.1 .
Thanks.

**Comment by anu171** [comment]
can you please explain what does it simply mean?or how can i install
cyberScan  in my machine???

**Comment by medbenali** [comment]
Hello romio, 

Juste clone the repository and access to it  , Cyberscan is installed in blackarch .
And maybe it will installed for another OS.
Thanks
